---
- name: Worker Tasks
  hosts: swarmWorker,swarmManager
  remote_user: ansible
  become: yes

  tasks:
  - name: Uninstalling vim on machine
    ansible.builtin.apt:
      name: vim
      state: absent

  - name: Check for test file
    stat:
      path: /etc/test.txt
    register: test_file

  - name: Create file if not exists
    file:
      path: /etc/test.txt
      state: absent
    when: test_file.stat.exists
