---
- name: Base configurations
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: Base packages through apt
    ansible.builtin.apt:
      name:
        - vim
        - inetutils-ping
        - vim
        - rsync
        - wget
        - curl
      state: present
